<a href="https://colab.research.google.com/github/amirafshari/pythonTutorial/blob/main/death_causes-24sep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [107]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('/content/number-of-deaths-by-risk-factor.csv')

In [3]:
data

,Entity,Code,Year,"Deaths that are from all causes attributed to high systolic blood pressure, in both sexes aged all ages","Deaths that are from all causes attributed to diet high in sodium, in both sexes aged all ages","Deaths that are from all causes attributed to diet low in whole grains, in both sexes aged all ages","Deaths that are from all causes attributed to alcohol use, in both sexes aged all ages","Deaths that are from all causes attributed to diet low in fruits, in both sexes aged all ages","Deaths that are from all causes attributed to unsafe water source, in both sexes aged all ages","Deaths that are from all causes attributed to secondhand smoke, in both sexes aged all ages",...,"Deaths that are from all causes attributed to drug use, in both sexes aged all ages","Deaths that are from all causes attributed to low bone mineral density, in both sexes aged all ages","Deaths that are from all causes attributed to vitamin a deficiency, in both sexes aged all ages","Deaths that are from all causes attributed to child stunting, in both sexes aged all ages","Deaths that are from all causes attributed to non-exclusive breastfeeding, in both sexes aged all ages","Deaths that are from all causes attributed to iron deficiency, in both sexes aged all ages","Deaths that are from all causes attributed to ambient particulate matter pollution, in both sexes aged all ages","Deaths that are from all causes attributed to low physical activity, in both sexes aged all ages","Deaths that are from all causes attributed to no access to handwashing facility, in both sexes aged all ages","Deaths that are from all causes attributed to high ldl cholesterol, in both sexes aged all ages"
0,Afghanistan,AFG,1990,25633.129,1044.9089,7077.3160,356.21470,3184.9550,3701.9940,4794.4650,...,173.57869,388.91074,2015.51150,7685.74270,2216.04150,563.81067,2782.4385,2636.64550,4825.3450,12704.7810
1,Afghanistan,AFG,1991,25871.803,1054.9584,7149.0854,363.73020,3248.3767,4309.2820,4921.0957,...,187.89368,388.78424,2056.35380,7885.67240,2501.02510,610.78830,2845.6702,2651.88650,5127.1780,12843.5130
2,Afghanistan,AFG,1992,26308.795,1074.6057,7297.3086,375.90024,3350.9207,5356.4980,5278.5186,...,210.81355,392.72090,2100.43100,8567.74000,3052.53880,699.58734,3030.8933,2687.92240,5888.8438,13125.6210
3,Afghanistan,AFG,1993,26961.360,1103.3705,7498.5340,388.57156,3479.8118,7151.5210,5734.0303,...,232.17093,410.67044,2315.59060,9875.29000,3725.87570,772.88920,3255.7598,2744.35990,7006.9080,13501.3545
4,Afghanistan,AFG,1994,27658.424,1133.8824,7697.5890,398.72700,3609.8315,7191.6390,6050.2290,...,247.29659,412.98883,2664.55370,11030.84800,3832.53170,811.97064,3400.9597,2805.21950,7421.1280,13872.5840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,11483.307,1062.7714,1353.5919,4853.71830,1820.3645,4335.9062,1613.8134,...,1067.76540,407.44086,137.89296,729.65375,733.78687,281.98135,2784.9744,309.46160,4328.0870,3276.1338
6836,Zimbabwe,ZWE,2016,11662.818,1081.5592,1382.9396,4915.49170,1854.2546,4244.4795,1625.2667,...,1041.80350,414.93375,100.74864,674.07230,699.98810,275.09952,2723.1400,318.11215,4294.5996,3346.3604
6837,Zimbabwe,ZWE,2017,11818.670,1097.7340,1408.9166,4991.75340,1882.9751,4192.6160,1624.9282,...,1007.37440,424.07550,82.42957,629.17920,678.33685,266.91394,2630.3557,326.67880,4250.6826,3410.7505
6838,Zimbabwe,ZWE,2018,12002.042,1116.5680,1439.0463,5044.16060,1917.0316,4012.9230,1627.9741,...,969.35500,433.54470,84.65486,606.91940,643.89320,260.99170,2599.9414,334.54236,4152.8130,3481.9556
6839,Zimbabwe,ZWE,2019,12240.987,1140.3761,1475.0681,5155.78900,1959.8661,3914.0618,1645.9760,...,962.71295,437.88790,81.38264,585.39320,630.75270,259.00020,2607.0251,344.59024,4113.1187,3571.3533

In [4]:
data.columns

Index(['Entity', 'Code', 'Year',
       'Deaths that are from all causes attributed to high systolic blood pressure, in both sexes aged all ages',
       'Deaths that are from all causes attributed to diet high in sodium, in both sexes aged all ages',
       'Deaths that are from all causes attributed to diet low in whole grains, in both sexes aged all ages',
       'Deaths that are from all causes attributed to alcohol use, in both sexes aged all ages',
       'Deaths that are from all causes attributed to diet low in fruits, in both sexes aged all ages',
       'Deaths that are from all causes attributed to unsafe water source, in both sexes aged all ages',
       'Deaths that are from all causes attributed to secondhand smoke, in both sexes aged all ages',
       'Deaths that are from all causes attributed to low birth weight, in both sexes aged all ages',
       'Deaths that are from all causes attributed to child wasting, in both sexes aged all ages',
       'Deaths that are from all causes attributed to unsafe sex, in both sexes aged all ages',
       'Deaths that are from all causes attributed to diet low in nuts and seeds, in both sexes aged all ages',
       'Deaths that are from all causes attributed to household air pollution from solid fuels, in both sexes aged all ages',
       'Deaths that are from all causes attributed to diet low in vegetables, in both sexes aged all ages',
       'Deaths that are from all causes attributed to smoking, in both sexes aged all ages',
       'Deaths that are from all causes attributed to high fasting plasma glucose, in both sexes aged all ages',
       'Deaths that are from all causes attributed to air pollution, in both sexes aged all ages',
       'Deaths that are from all causes attributed to high body-mass index, in both sexes aged all ages',
       'Deaths that are from all causes attributed to unsafe sanitation, in both sexes aged all ages',
       'Deaths that are from all causes attributed to drug use, in both sexes aged all ages',
       'Deaths that are from all causes attributed to low bone mineral density, in both sexes aged all ages',
       'Deaths that are from all causes attributed to vitamin a deficiency, in both sexes aged all ages',
       'Deaths that are from all causes attributed to child stunting, in both sexes aged all ages',
       'Deaths that are from all causes attributed to non-exclusive breastfeeding, in both sexes aged all ages',
       'Deaths that are from all causes attributed to iron deficiency, in both sexes aged all ages',
       'Deaths that are from all causes attributed to ambient particulate matter pollution, in both sexes aged all ages',
       'Deaths that are from all causes attributed to low physical activity, in both sexes aged all ages',
       'Deaths that are from all causes attributed to no access to handwashing facility, in both sexes aged all ages',
       'Deaths that are from all causes attributed to high ldl cholesterol, in both sexes aged all ages'],
      dtype='object')

In [6]:
data['Entity'].unique()

array(['Afghanistan', 'African Region (WHO)', 'Albania', 'Algeria',
       'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Cape Verde', 'Central African Republic', 'Chad',
       'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'East Asia & Pacific (WB)',
       'East Timor', 'Eastern Mediterranean Region (WHO)', 'Ecuador',
       'Egypt', 'El Salvador', 'England', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Europe & Central Asia (WB)',
       'European Region (WHO)', 'Fiji', 'Finland', 'France', 'G20',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'High Income (WB)', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos',
       'Latin America & Caribbean (WB)', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Low Income (WB)',
       'Lower Middle Income (WB)', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Micronesia (country)',
       'Middle East & North Africa (WB)', 'Middle Income (WB)', 'Moldova',
       'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North America (WB)', 'North Korea', 'North Macedonia',
       'Northern Ireland', 'Northern Mariana Islands', 'Norway',
       'OECD Countries', 'Oman', 'Pakistan', 'Palau', 'Palestine',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Region of the Americas (WHO)', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Asia (WB)', 'South Korea', 'South Sudan',
       'South-East Asia Region (WHO)', 'Spain', 'Sri Lanka',
       'Sub-Saharan Africa (WB)', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Wales', 'Western Pacific Region (WHO)',
       'World', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [101]:
world = data[data['Entity'] == 'World']

In [13]:
world

,Entity,Code,Year,"Deaths that are from all causes attributed to high systolic blood pressure, in both sexes aged all ages","Deaths that are from all causes attributed to diet high in sodium, in both sexes aged all ages","Deaths that are from all causes attributed to diet low in whole grains, in both sexes aged all ages","Deaths that are from all causes attributed to alcohol use, in both sexes aged all ages","Deaths that are from all causes attributed to diet low in fruits, in both sexes aged all ages","Deaths that are from all causes attributed to unsafe water source, in both sexes aged all ages","Deaths that are from all causes attributed to secondhand smoke, in both sexes aged all ages",...,"Deaths that are from all causes attributed to drug use, in both sexes aged all ages","Deaths that are from all causes attributed to low bone mineral density, in both sexes aged all ages","Deaths that are from all causes attributed to vitamin a deficiency, in both sexes aged all ages","Deaths that are from all causes attributed to child stunting, in both sexes aged all ages","Deaths that are from all causes attributed to non-exclusive breastfeeding, in both sexes aged all ages","Deaths that are from all causes attributed to iron deficiency, in both sexes aged all ages","Deaths that are from all causes attributed to ambient particulate matter pollution, in both sexes aged all ages","Deaths that are from all causes attributed to low physical activity, in both sexes aged all ages","Deaths that are from all causes attributed to no access to handwashing facility, in both sexes aged all ages","Deaths that are from all causes attributed to high ldl cholesterol, in both sexes aged all ages"
6720,World,OWID_WRL,1990,6787714.5,1320338.0,1178221.8,1639872.2,795603.40,2442070.5,1161963.1,...,235888.02,207366.97,207555.220,833448.56,505469.66,73461.060,2047171.0,452167.47,1200094.00,3002611.0
6721,World,OWID_WRL,1991,6888724.5,1331430.2,1197636.4,1676080.6,805993.50,2450943.8,1165940.0,...,252438.88,211921.06,203551.690,817068.30,497187.28,72379.370,2087355.1,460917.70,1200348.90,3030906.0
6722,World,OWID_WRL,1992,7023441.5,1348867.0,1223711.1,1723426.2,821076.70,2425768.5,1173047.5,...,269331.80,216470.62,198336.600,796502.75,478093.88,72502.980,2138114.5,472631.30,1190921.80,3076783.5
6723,World,OWID_WRL,1993,7240557.5,1372509.9,1271470.1,1787248.6,844230.75,2361329.8,1183325.8,...,289135.16,223118.44,189702.840,771675.56,461114.44,70802.300,2210730.0,491233.06,1162487.80,3181351.0
6724,World,OWID_WRL,1994,7378238.0,1383663.9,1301408.9,1841376.8,859534.40,2310204.8,1184536.0,...,309633.97,227824.56,183165.190,750688.90,445705.38,70290.900,2265125.0,503301.40,1141067.40,3239905.8
6725,World,OWID_WRL,1995,7444400.5,1388701.0,1311139.9,1866760.8,865099.94,2253179.2,1178298.6,...,326355.78,231800.40,177588.190,729487.75,427443.56,69320.530,2301686.5,512355.28,1118113.40,3244864.5
6726,World,OWID_WRL,1996,7499709.0,1391525.1,1313663.4,1870992.6,870446.56,2203646.0,1171342.5,...,337404.75,236373.94,171320.480,703712.75,409781.84,68509.500,2340252.8,518808.30,1095440.10,3231197.8
6727,World,OWID_WRL,1997,7579361.0,1394395.1,1320627.4,1876174.4,879645.06,2171865.0,1165820.5,...,345395.12,242189.06,164328.020,678544.10,392772.20,68874.110,2397084.5,526468.80,1079870.50,3227647.0
6728,World,OWID_WRL,1998,7653805.0,1397467.1,1328164.8,1894286.2,883806.70,2140947.5,1156209.9,...,357228.60,247538.64,158344.060,653014.00,378471.72,68577.090,2455464.5,535972.06,1062523.10,3227356.2
6729,World,OWID_WRL,1999,7805180.0,1418036.2,1354556.0,1935616.8,895248.06,2099432.2,1154278.1,...,373305.22,253734.53,153903.390,626193.90,364995.16,68367.420,2533061.5,548853.40,1043004.25,3280738.5
6730,World,OWID_WRL,2000,7941549.5,1445663.8,1375419.9,1978982.1,910169.40,2049815.2,1155066.1,...,387019.38,261209.34,146252.220,596760.50,351716.06,67826.600,2607106.8,558136.60,1021162.70,3317574.0
6731,World,OWID_WRL,2001,8075036.5,1466830.1,1398632.5,2011933.6,922030.94,1994000.8,1154456.5,...,392717.66,269611.12,136990.390,564423.10,338309.94,66550.880,2669149.0,568285.25,993946.80,3360051.5
6732,World,OWID_WRL,2002,8259230.0,1500028.0,1432244.8,2062868.4,936759.56,1934977.9,1159897.6,...,397220.70,280433.56,126977.980,533554.90,325524.10,64756.990,2744254.2,580620.06,968064.90,3430174.8
6733,World,OWID_WRL,2003,8379687.0,1524748.6,1455590.4,2108453.5,942517.00,1873267.9,1159365.4,...,401104.97,291242.34,116576.414,503048.25,313891.06,62770.410,2804077.0,589602.50,942329.60,3477293.5
6734,World,OWID_WRL,2004,8399163.0,1539206.9,1457698.8,2138328.0,937529.40,1805630.8,1152007.6,...,405218.72,298769.66,106920.945,474028.97,302616.34,61561.310,2844690.2,591308.40,914205.90,3474040.5
6735,World,OWID_WRL,2005,8549944.0,1556959.8,1485084.9,2184611.0,946126.06,1767662.0,1155247.9,...,416768.62,311015.90,95847.266,445544.47,291328.78,61119.050,2912992.2,604191.25,897688.10,3537654.8
6736,World,OWID_WRL,2006,8575737.0,1546630.0,1484696.4,2171665.8,938737.44,1752216.0,1143361.9,...,417386.34,319113.90,83527.780,413096.50,281709.22,59777.560,2951444.0,612109.90,889970.90,3532881.5
6737,World,OWID_WRL,2007,8679507.0,1555050.5,1498941.6,2184676.2,938621.25,1722904.4,1139415.6,...,419032.56,327731.47,74707.820,384634.20,270177.00,57836.867,3032978.2,624275.40,875743.50,3566949.2
6738,World,OWID_WRL,2008,8873304.0,1585059.6,1527980.5,2228186.5,946045.56,1694361.0,1147640.8,...,423060.25,337135.03,69095.560,360203.72,259063.90,56450.008,3154919.5,642702.56,860089.56,3639990.5
6739,World,OWID_WRL,2009,8990223.0,1609279.2,1540396.1,2223072.8,942559.25,1635489.5,1147592.1,...,419344.25,339421.30,63769.906,336830.53,247990.38,55249.190,3252001.8,655754.20,832772.94,3670389.2
6740,World,OWID_WRL,2010,9181355.0,1644632.5,1569687.1,2249855.0,950118.60,1592303.1,1156229.0,...,420751.78,346141.38,59766.840,317920.88,236921.69,54115.160,3359355.0,672215.00,809831.70,3746423.5
6741,World,OWID_WRL,2011,9324965.0,1669140.9,1591653.4,2235098.0,954610.80,1566353.5,1163170.4,...,423500.44,354746.53,56697.074,301832.90,226513.64,52796.562,3462498.2,685827.56,790259.10,3796330.5
6742,World,OWID_WRL,2012,9470980.0,1688558.2,1614793.0,2247303.8,959393.30,1504617.0,1169127.6,...,424783.28,362471.88,50333.707,281589.25,214395.05,50747.793,3575957.2,697604.90,762949.94,3850347.2
6743,World,OWID_WRL,2013,9622330.0,1705269.9,1639467.5,2258003.2,964258.90,1461534.5,1180237.8,...,429021.66,373945.90,43588.400,262374.97,203990.50,49599.990,3698902.2,714201.20,744109.25,3909372.5
6744,World,OWID_WRL,2014,9765811.0,1723074.0,1659528.2,2270896.0,967793.90,1406151.1,1191687.0,...,438384.80,383968.34,38614.645,243105.83,192370.47,47387.098,3792901.2,729791.75,720558.30,3959287.0
6745,World,OWID_WRL,2015,9999740.0,1753288.6,1702413.4,2304268.5,983682.00,1363038.1,1209810.6,...,452151.20,395856.80,34267.460,225277.58,181113.14,45726.430,3870691.2,749003.10,699664.50,4063586.8
6746,World,OWID_WRL,2016,10190860.0,1785454.9,1730299.0,2332374.0,996498.70,1327636.8,1226823.4,...,465395.53,405812.53,30436.084,208613.62,169677.83,44486.312,3875979.2,770863.90,681615.70,4127272.0
6747,World,OWID_WRL,2017,10351721.0,1811392.2,1758037.0,2355671.5,1008137.60,1319413.5,1243584.4,...,472655.75,414523.80,28132.988,195112.14,160458.47,43314.375,3882444.0,798187.10,670169.50,4188135.0
6748,World,OWID_WRL,2018,10589176.0,1842749.6,1802322.9,2393321.2,1027420.60,1270273.0,1272136.9,...,481976.40,426725.94,26127.377,178086.23,148105.00,42953.020,3987348.5,817081.00,647002.06,4292468.0
6749,World,OWID_WRL,2019,10845595.0,1885355.9,1844836.1,2441973.5,1046014.90,1230153.9,1304318.4,...,494491.70,437884.40,23849.850,164237.11,139731.90,42349.240,4140971.0,831502.00,627918.90,4396983.5

In [44]:
world_2019 = world[world['Year'] == 2019]

To Do: How to find the second/third max instead of the max value?

# Max Cause Each Year - WW

In [ ]:
death_max_year = []

for year in world['Year'].values:
  df_each_year = world[world['Year'] == year]
  max_value = float(df_each_year.max(axis=1).values)
  column = df_each_year[df_each_year == max_value].dropna(axis=1).columns.values[0]
  item = (column, year, max_value)

  death_max_year.append(item)

death_max_year

# Min Cause Each Year - WW
To Do: (NOT WORKING)

In [112]:
world[world['Year'] == 2019].min(axis=1)

6749    2019.0
dtype: float64

In [99]:
df_each_year.min(axis=1)

6749    2019.0
dtype: float64

In [102]:
death_min_year = []

for year in world['Year'].values:
  df_each_year = world[world['Year'] == year]
  min_value = float(df_each_year.min(axis=1).values)
  column = df_each_year[df_each_year == min_value].dropna(axis=1).columns.values[0]
  item = (column, year, min_value)

  death_min_year.append(item)

death_min_year

[('Year', 1990, 1990.0),
 ('Year', 1991, 1991.0),
 ('Year', 1992, 1992.0),
 ('Year', 1993, 1993.0),
 ('Year', 1994, 1994.0),
 ('Year', 1995, 1995.0),
 ('Year', 1996, 1996.0),
 ('Year', 1997, 1997.0),
 ('Year', 1998, 1998.0),
 ('Year', 1999, 1999.0),
 ('Year', 2000, 2000.0),
 ('Year', 2001, 2001.0),
 ('Year', 2002, 2002.0),
 ('Year', 2003, 2003.0),
 ('Year', 2004, 2004.0),
 ('Year', 2005, 2005.0),
 ('Year', 2006, 2006.0),
 ('Year', 2007, 2007.0),
 ('Year', 2008, 2008.0),
 ('Year', 2009, 2009.0),
 ('Year', 2010, 2010.0),
 ('Year', 2011, 2011.0),
 ('Year', 2012, 2012.0),
 ('Year', 2013, 2013.0),
 ('Year', 2014, 2014.0),
 ('Year', 2015, 2015.0),
 ('Year', 2016, 2016.0),
 ('Year', 2017, 2017.0),
 ('Year', 2018, 2018.0),
 ('Year', 2019, 2019.0)]

# Iran